using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BackendCapstone.Models;
using BackendCapstone.Services;
using System.Net;
using System.Web.Http;
using System.Net.Http;
using Example;

namespace BackendCapstone.Controllers
{
    [RoutePrefix("api/emergencyreports")]
    public class EmergencyReportsController : ApiController
    {
        [Route, HttpGet]
        public HttpResponseMessage GetEmergencyReportsList()
        {
            var repository = new EmergencyReportsRepository();
            var result = repository.GetAllEmergencyReports();

            return Request.CreateResponse(HttpStatusCode.OK, result);
        }

        [Route("{Id}"), HttpGet]
        public HttpResponseMessage GetSingleEmergencyReport(int id)
        {
            var repository = new EmergencyReportsRepository();
            var result = repository.GetEmergencyReportById(id);

            return Request.CreateResponse(HttpStatusCode.OK, result);
        }

        [Route(""), HttpGet]
        public HttpResponseMessage GetEmergencyReportsByProperty(string property)
        {
            var repository = new EmergencyReportsRepository();
            var result = repository.GetAllEmergencyReports().Where(er => er.PropertyName == property);

            return Request.CreateResponse(HttpStatusCode.OK, result);
        }

        [Route, HttpPost]
        public HttpResponseMessage AddEmergencyReport(EmergencyReportsDto newEmergencyReport)
        {
            var repository = new EmergencyReportsRepository();
            var id = repository.Create(newEmergencyReport);
            var emergencyReportToSend = repository.GetEmergencyReportForEmail(id);

            var bodyOfEmail =
$@"Below is an emergency report generated by the on call manager:<br/>
Date: {emergencyReportToSend.Date} <br/>
Manager Name: {emergencyReportToSend.ManagerName} <br/>
Caller: {emergencyReportToSend.Caller}<br/>
Caller Phone Number: {emergencyReportToSend.CallerPhoneNumber}<br/>
Property Name: {emergencyReportToSend.PropertyName}<br/>
Address: {emergencyReportToSend.Address}<br/>
Incident Description: {emergencyReportToSend.IncidentDescription}<br/>
Action Taken: {emergencyReportToSend.ActionTaken}<br/>
";

            SendgridEmail.Execute(emergencyReportToSend.ManagerEmail, emergencyReportToSend.ManagerName, bodyOfEmail);

      
            return Request.CreateResponse(HttpStatusCode.Created);
        }

        [Route("{id}"), HttpPut]
        public HttpResponseMessage EditEmergencyReport(int Id, EmergencyReportsDto emergencyreport)
        {
            var repository = new EmergencyReportsRepository();
            var result = repository.Edit(Id, emergencyreport);

            if (result)
                return Request.CreateResponse(HttpStatusCode.OK);
            return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, "Report could not be updated");
        }
    }
}